"""init schema

Revision ID: 45e930d4e7dc
Revises: 
Create Date: 2026-05-26 17:09:06.074520
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '45e930d4e7dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hash_blacklist',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sha256', name=op.f('pk_hash_blacklist'))
    )
    op.create_table('ip_quotas',
    sa.Column('ip', postgresql.INET(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('upload_count', sa.Integer(), nullable=False),
    sa.Column('upload_bytes', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('ip', 'date', name='pk_ip_quotas')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=16), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_downloads', sa.Integer(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_created_from', postgresql.INET(), nullable=True),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_shares_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shares'))
    )
    op.create_index(op.f('ix_shares_code'), 'shares', ['code'], unique=True)
    op.create_index(op.f('ix_shares_expires_at'), 'shares', ['expires_at'], unique=False)
    op.create_index('ix_shares_owner_created', 'shares', ['owner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_shares_owner_id'), 'shares', ['owner_id'], unique=False)
    op.create_table('download_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('share_id', sa.UUID(), nullable=False),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('ua', sa.String(length=512), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['share_id'], ['shares.id'], name=op.f('fk_download_logs_share_id_shares'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_download_logs'))
    )
    op.create_index(op.f('ix_download_logs_downloaded_at'), 'download_logs', ['downloaded_at'], unique=False)
    op.create_index(op.f('ix_download_logs_share_id'), 'download_logs', ['share_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('share_id', sa.UUID(), nullable=False),
    sa.Column('reporter_ip', postgresql.INET(), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['share_id'], ['shares.id'], name=op.f('fk_reports_share_id_shares'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_share_id'), 'reports', ['share_id'], unique=False)
    op.create_table('share_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('share_id', sa.UUID(), nullable=False),
    sa.Column('original_name', sa.String(length=512), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=127), nullable=True),
    sa.Column('tos_uri', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['share_id'], ['shares.id'], name=op.f('fk_share_files_share_id_shares'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_share_files'))
    )
    op.create_index(op.f('ix_share_files_sha256'), 'share_files', ['sha256'], unique=False)
    op.create_index(op.f('ix_share_files_share_id'), 'share_files', ['share_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_share_files_share_id'), table_name='share_files')
    op.drop_index(op.f('ix_share_files_sha256'), table_name='share_files')
    op.drop_table('share_files')
    op.drop_index(op.f('ix_reports_share_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_download_logs_share_id'), table_name='download_logs')
    op.drop_index(op.f('ix_download_logs_downloaded_at'), table_name='download_logs')
    op.drop_table('download_logs')
    op.drop_index(op.f('ix_shares_owner_id'), table_name='shares')
    op.drop_index('ix_shares_owner_created', table_name='shares')
    op.drop_index(op.f('ix_shares_expires_at'), table_name='shares')
    op.drop_index(op.f('ix_shares_code'), table_name='shares')
    op.drop_table('shares')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('ip_quotas')
    op.drop_table('hash_blacklist')
    # ### end Alembic commands ###
